apiVersion: batch/v1
kind: CronJob
metadata:
  name: clearsessions
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: django-app-clearsessions
            image: django_app:minikube
            envFrom:
              - configMapRef:
                  name: django-config-20230202-v7
            imagePullPolicy: IfNotPresent
            command:
            - python
            - manage.py
            - clearsessions
          restartPolicy: Never